[package]
name = "deko_os"
version = "0.1.0"
authors = ["dekokun <dekokun@hatena.ne.jp>"]

[profile.dev]

[profile.release]

[dependencies]
bootloader_precompiled = "0.2.0"
volatile = "0.2.4"

[package.metadata.bootimage]
default-target = "x86_64-deko_os.json"
